#\!/bin/bash

# List of functions from buttons
functions=(
"acceptNotice"
"approveRegistration"
"changeDocument"
"checkContractResources"
"checkExemptionStatus"
"checkRole"
"closeAcceptModal"
"closeAuditModal"
"closeMintModal"
"closeRegistrationModal"
"closeRegistrationSuccessModal"
"closeTransactionResultModal"
"closeTxModal"
"connectContracts"
"connectWallet"
"copyAddress"
"copyDebugInfo"
"copyEncryptionKey"
"copyTxHash"
"copyWalletAddress"
"createLegalNotice"
"debugAlerts"
"debugCheckRoles"
"deleteRegistration"
"dismissRegistrationNotice"
"editRegistration"
"exportReceipt"
"exportRegistrations"
"fetchAllRegistrations"
"fixMyFeeExemption"
"grantRole"
"openAuditModal"
"openMintModal"
"openRegistrationForUser"
"openRegistrationModal"
"performAudit"
"refreshDeliveryStatus"
"refreshMyAlerts"
"refreshPendingRegistrations"
"refreshWalletStatus"
"rejectRegistration"
"removeLawEnforcementExemption"
"saveGitHubSettings"
"savePinataKeys"
"saveReceiptAsHTML"
"saveRegistrationEdit"
"setLawEnforcementExemption"
"showDelegateEnergyModal"
"showMintStep"
"submitAdminRegistration"
"submitRegistration"
"switchTab"
"testGitHubConnection"
"testPinataConnection"
"toggleFAQ"
"toggleTokenVisibility"
"updateCreationFee"
"updateFeeCollector"
"updateResourceSponsorship"
"updateServiceFee"
"updateSponsorshipFee"
"useConnectedAddress"
"useConnectedAddressForExemption"
"useConnectedAddressForFeeCollector"
"verifyTransaction"
"viewContractOnTronscan"
"withdrawFromContract"
)

echo "Checking which functions are missing..."
echo "======================================="

for func in "${functions[@]}"; do
    if grep -q "function $func\|$func.*=.*function\|const $func.*=\|async function $func" index.html; then
        echo "✅ $func"
    else
        echo "❌ $func - MISSING"
    fi
done
